#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git firstw

COMPOSE_INSTALLED=$(which docker-compose)

if [ -z $COMPOSE_INSTALLED ]; then
    pip install --upgrade docker-compose==1.2.0
fi

apt-get install -y git
